---
title: "Cálculo de 2^-ΔΔCT para miRNAs"
author: "Ana De León"
date: "2024-05-20"
output: html_document
---

```{r}
library(pacman)
p_load("vroom", "dplyr", "ggplot2", "ggrepel", "matrixTests")
```
Cargar los datos

```{r}
data_url <- "https://raw.githubusercontent.com/ManuelLaraMVZ/Transcript-mica/main/examen2"
data <- read.csv(data_url)
head(data)
```
Filtrar datos de interés
```{r}
data_target <- data %>% 
  filter(Type == "Target") %>% 
  select(1, 3, 4, 5, 6, 7, 8)
```
Filtrar datos de control
```{r}
control <- data %>% 
  filter(Type == "Selected Control") %>% 
  select(1,3,4,5,6,7,8)
```
Calcular medias de control
```{r}
meanT1 <- mean(control$T1)
meanT2 <- mean(control$T2)
meanT3 <- mean(control$T3)
meanC1 <- mean(control$C1)
meanC2 <- mean(control$C2)
meanC3 <- mean(control$C3)
```
Calcular ΔCT
```{r}
Copiar código
DCT <- data_target %>% 
  mutate(DCT1 = T1 - meanT1, DCT2 = T2 - meanT2, DCT3 = T3 - meanT3,
         DCC1 = C1 - meanC1, DCC2 = C2 - meanC2, DCC3 = C3 - meanC3)
```
Calcular ΔΔCT
```{r}
DCT <- DCT %>% 
  mutate(DDCT1 = DCT1 - DCC1, DDCT2 = DCT2 - DCC2, DDCT3 = DCT3 - DCC3)
```
Calcular 2^-ΔΔCT
```{r}
DosDDCT <- DCT %>% 
  mutate(A = 2^(-DDCT1), B = 2^(-DDCT2), C = 2^(-DDCT3)) %>% 
  select(1, A, B, C)
DosDDCT
markdown
```

